### ISSUE TITLE
Fully functional web portal

### ISSUE THREAD

**Issue by nielsdrost** [c3s-magic/c3s-magic-frontend#112]
The portal should not contain any issues hindering the basic functioning/usage of the site.

**Comment by fdiblen** [comment]
We fixed most of the issues. Any issues to mention? Otherwise we can close this issue.

**Comment by nielsdrost** [comment]
This is an Epic. In ZenHub you can view the other issues still remaining.

**Comment by nielsdrost** [comment]
Done.
